# Generated by Django 2.2 on 2020-04-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_desc121_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
